metadata.format.version = "1.1"

[versions]

kotlin = "2.2.21"
ksp = "2.2.21-2.0.4" # Not forget to keep in sync with kotlin version

lwjgl = "3.3.6"
gson = "2.12.1"
annotations = "26.0.2"
fastutil = "8.5.15"
oshi = "6.6.6"
joml = "1.10.8"
commons-io = "2.18.0"
detekt = "1.23.8"

[libraries]

annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }
ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
joml = { group = "org.joml", name = "joml", version.ref = "joml" }
oshi = { group = "com.github.oshi", name = "oshi-core", version.ref = "oshi" }
commonsIo = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }

lwjgl-lib = { group = "org.lwjgl", name = "lwjgl", version.ref = "lwjgl" }
lwjgl-glfw = { group = "org.lwjgl", name = "lwjgl-glfw", version.ref = "lwjgl" }
lwjgl-egl = { group = "org.lwjgl", name = "lwjgl-egl", version.ref = "lwjgl" }
lwjgl-stb = { group = "org.lwjgl", name = "lwjgl-stb", version.ref = "lwjgl" }
lwjgl-vma = { group = "org.lwjgl", name = "lwjgl-vma", version.ref = "lwjgl" }
lwjgl-shaderc = { group = "org.lwjgl", name = "lwjgl-shaderc", version.ref = "lwjgl" }
lwjgl-assimp = { group = "org.lwjgl", name = "lwjgl-assimp", version.ref = "lwjgl" }
lwjgl-opengl = { group = "org.lwjgl", name = "lwjgl-opengl", version.ref = "lwjgl" }
lwjgl-opengles = { group = "org.lwjgl", name = "lwjgl-opengles", version.ref = "lwjgl" }
lwjgl-vulkan = { group = "org.lwjgl", name = "lwjgl-vulkan", version.ref = "lwjgl" }
lwjgl-openal = { group = "org.lwjgl", name = "lwjgl-openal", version.ref = "lwjgl" }

# Plugins
plugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "ksp" }
plugin-detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
